//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSeller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieSeller.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MovieSellerApp.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Booking.
        /// </summary>
        public static string ButtonContentBuyBooking {
            get {
                return ResourceManager.GetString("ButtonContentBuyBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SelectedMovie.
        /// </summary>
        public static string ButtonContentChangeMovie {
            get {
                return ResourceManager.GetString("ButtonContentChangeMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ButtonContentRemoveSession {
            get {
                return ResourceManager.GetString("ButtonContentRemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete a movie session .
        /// </summary>
        public static string ConfirmDeleteTextPart1 {
            get {
                return ResourceManager.GetString("ConfirmDeleteTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ? These changes cannot be reversed..
        /// </summary>
        public static string ConfirmDeleteTextPart2 {
            get {
                return ResourceManager.GetString("ConfirmDeleteTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string DataGridHeaderBegin {
            get {
                return ResourceManager.GetString("DataGridHeaderBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current MaxCount.
        /// </summary>
        public static string DataGridHeaderCurrentCount {
            get {
                return ResourceManager.GetString("DataGridHeaderCurrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string DataGridHeaderEnd {
            get {
                return ResourceManager.GetString("DataGridHeaderEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max MaxCount.
        /// </summary>
        public static string DataGridHeaderMaxCount {
            get {
                return ResourceManager.GetString("DataGridHeaderMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedMovie.
        /// </summary>
        public static string DataGridHeaderMovieName {
            get {
                return ResourceManager.GetString("DataGridHeaderMovieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SelectedMovie.
        /// </summary>
        public static string MenuItemAddMovieSession {
            get {
                return ResourceManager.GetString("MenuItemAddMovieSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string MovieDuration {
            get {
                return ResourceManager.GetString("MovieDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Count.
        /// </summary>
        public static string MovieSessionBookingCount {
            get {
                return ResourceManager.GetString("MovieSessionBookingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Count.
        /// </summary>
        public static string MovieSessionBookingMaxCount {
            get {
                return ResourceManager.GetString("MovieSessionBookingMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewButtonText {
            get {
                return ResourceManager.GetString("NewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
    }
}
